# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd0b80c56ad978b5584fdc5c462c7702e7236b30b8d115b220ce933d33f7031f2fd1e09be5014226033bf55c35bf886b51a46774487932c8260443301d044f6

test:
  secret_key_base: 397aa0b7470bde0e7d8466dec2a8ab9a93e9daaa57bc2e3cf2d7882aed010082d5d4ec0722bcb1ba0bd654cf2ccae2f734371f0a76db3160acc8b3ccddc0e0c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
